version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/go/*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "npm"
    directories:
      - "/node/*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "node"

  - package-ecosystem: "pip"
    directories:
      - "/python/*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
