name: Proof HTML
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@3cb0083534425b4902e6e77ac26ac3fe5b718f51  # v2.2.4
        with:
          directory: ./
