name: Proof HTML
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: anishathalye/proof-html@a76b66427e600c6992e8937a741afffd2264a613  # v2.2.3
        with:
          directory: ./
